### ISSUE TITLE
Encountered an error while parsing.

### ISSUE THREAD

**Issue by stforehand** [n8felton/Firefox-ADMX#18]
Hi there! I recently had a need to deploy Firefox settings, and after installing your admin templates to the central store, I get the following:

![firefox admx](https://cloud.githubusercontent.com/assets/6360936/16244364/3428b74c-37c1-11e6-8f83-3e36bbc5808c.png)

I renamed the files to Firefox.XXX because I saw that seemed to work for another user. The same happens with an unmodified file.

**Comment by n8felton** [comment]
Closing as a duplicate to #1 .
