### ISSUE TITLE
Crash at creating a GPO

### ISSUE THREAD

**Issue by cyco1982** [n8felton/Firefox-ADMX#23]
Hello,

following data:
Domain-Controller: Server 2012R2
Domain-Level: 2008R2

Error-Massage:
![2017-03-02_161130](https://cloud.githubusercontent.com/assets/26143943/23513030/fa102800-ff62-11e6-8474-103d7b906c7d.png)

Could you help, please?

**Comment by 91jme** [comment]
"de-DE/mozilla.adml" is missing the "MOZILLA_FIREFOX_LOCKED_CUSTOM_USERAGENT" string definition.

Adding the below two lines to your de-DE/mozilla.adml file, anywhere between lines 6 and 42 should fix:

`<string id="MOZILLA_FIREFOX_LOCKED_CUSTOM_USERAGENT">Brauch User-Agent</string>`

`<string id="MOZILLA_FIREFOX_LOCKED_CUSTOM_USERAGENT_Help">&#220;berschreiben default user-agent</string>`

I Google'd the German translations, apologies if they don't make sense.

**Comment by n8felton** [comment]
Fixed with #24. Thanks to @91jme for the PR.
